### ISSUE TITLE
error with gamedata

### ISSUE THREAD

**Issue by moidu21** [anno-mods/FileDBReader#40]
when i try to decompress gamedata (data25.rda dlc12 map) i get this error

http://quentfr21.free.fr/error.png

thanks in advance

Edit: i'm on pre-release 2.3.99

**Comment by taubenangriff** [comment]
So I guess some new stuff has been added, which is atm just interpreted as default (Int32). For Bytesize 1, that should be all booleans, 2 should be Int16 and 8 should be Int64, in case you wanna fix the interpreter for yourself now. (PR would be very welcome in that case)

But I can also fix this sometime in the future by myself.
