### ISSUE TITLE
ctt problem

### ISSUE THREAD

**Issue by moidu21** [anno-mods/FileDBReader#44]
hello i try to use the ctt.xml fileformat but it always fail with this

C:\anno 1800 modding\FileDBReadernew>FileDBReader.exe decompress -f 2x18.ctt -i fileformats/ctt.xml -y
[READER]: Autodetected FileVersion = Version1
Terminated conversion of 2x18.ctt because of an unknown Error.

how can i solve this ?

**Comment by taubenangriff** [comment]
https://github.com/anno-mods/FileDBReader/wiki/How-Island-Files-work#ctt-files

https://github.com/lukts30/ctt_helper
